title: Subramanya N
email: snagabhushan@umass.edu
description: '"The harder you work, the luckier you get." -- Gary Player'
baseurl: ""
url: "http://subramanya1997.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge