title: Subramanya N
email: 
description: "Computer Engineer."
baseurl: ""
url: "http://subramanya1997.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge